site_name: vitrum

theme:
  name: "material"

plugins:
  - search


nav:
    - Installation: vitrum/install.md
    - Quick start: vitrum/quickstart.md
    - Workflow: vitrum/workflow.md
    - Scattering: vitrum/scattering.md
    - Dynamics analysis: vitrum/dynamics.md
    - BALACE: vitrum/balace.md
    - Utilities: vitrum/utilities.md
#    - Utilities: pacemaker/utilities.md
#    - FAQs: pacemaker/faq.md