site_name: vitrum

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Installation: vitrum/install.md
    - Quick start: vitrum/quickstart.md
    - Scattering: vitrum/scattering.md
    - Coordination: vitrum/coordination.md
    - Diffusion analysis: vitrum/dynamics.md
    - Diffusion analysis: vitrum/rings.md
    - BALACE: vitrum/balace.md
    - Utilities: vitrum/utilities.md
    - Extended ASE Atoms: vitrum/glass_atoms.md

#    - FAQs: pacemaker/faq.md