site_name: vitrum

theme:
  name: "material"
  logo: vitrum_light.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Installation: vitrum/install.md
    - Quick start: vitrum/quickstart.md
    - Scattering: vitrum/scattering.md
    - Coordination: vitrum/coordination.md
    - Diffusion analysis: vitrum/dynamics.md
    - Ring analysis: vitrum/rings.md
    - Void analysis: vitrum/voids.md
    - Persistent homology: vitrum/persistent_homology.md
    - Structure generation: vitrum/structure_gen.md
    - MLIP evaluation: vitrum/mlip_functions.md
    - BALACE: vitrum/balace.md
    - Utilities: vitrum/utilities.md
    - Extended ASE Atoms: vitrum/glass_atoms.md
    - Known issues: vitrum/known_issues.md

#    - FAQs: pacemaker/faq.md